abstract: Math::Symbolic with lots of plugins
author: Steffen Mueller
build_requires: 
  Test::Pod: 1
  Test::Pod::Coverage: 1
distribution_type: module
generated_by: Module::Install version 0.63
license: perl
name: Task-Math-Symbolic
no_index: 
  directory: 
    - inc
    - t
recommends: 
  Math::Symbolic::Custom::CCompiler: 0
requires: 
  Math::Symbolic: 0.163
  Math::Symbolic::Custom::Contains: 0
  Math::Symbolic::Custom::ErrorPropagation: 0
  Math::Symbolic::Custom::Pattern: 0
  Math::Symbolic::Custom::Simplification: 0
  Math::Symbolic::Custom::Transformation: 0
  Math::SymbolicX::BigNum: 0
  Math::SymbolicX::Complex: 0
  Math::SymbolicX::Inline: 0
  Math::SymbolicX::NoSimplification: 0
  Math::SymbolicX::ParserExtensionFactory: 0
  Math::SymbolicX::Statistics::Distributions: 0
  perl: 5.6.0
version: 1.01
